[package]
name = "netmic-ui"
version = "0.1.0"
edition = "2021"
license = "MIT"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tracing = "0.1"
netmic-proto = { path = "../../../crates/netmic-proto" }
netmic-client = { path = "../../../crates/netmic-client" }
